### PR TITLE
Basic algorithm for dividing players into teams (draft command)

### PR DESCRIPTION
**Pull request by fbosnic**
Exact algorithm for dividing players into teams.
Looks at all possible division and chooses one according to something akin to a Gibbs measure

### CODE REVIEW

**Comment by eliobartos** [comment]
I get an error when moved to this branch and run `frank draft`

But need more time to check

**Comment by eliobartos** [comment]
Screenshot 2022-03-31 at 09 00 01

On top line you can see the command I entered. Rest is the error backlog. 
If it works for you maybe we have problems with package versions/python version...

**Comment by fbosnic** [comment]
Got the same problem.
Can you check `DATA/matches.csv` file, the last line might be corrupted (at least it was for me).

**Comment by eliobartos** [comment]
Draft now works. But draft is automatically adding new matches to matches.csv, that may not be desireable behaviour. Maybe there should be a flag whether to add this draft result to matches. Or additional question do you want to add this match, but seems more tedious.

Something like 
frank draft --add igrac1 igrac2 ..... igrac 10 

if you want to add the result to csv

**Comment by fbosnic** [comment]
Yeah, good idea. My original idea was to always add matches after draft but to have an easy way of removing matches which have not been scored. Currently this work with `frank remove matches all` but I don't like it.
All in all, I'll add a flag `--discard` which will not store the drafted match. The default behavior will be to store it.
Will create a special command for removing all non-scored matches

**Comment by eliobartos** [comment]
Tried it and it works.

**Comment by eliobartos** [comment]
This non-scored also works but can't be found through app documentation. Tried, frank --help, frank remove --help, frank remove matches --help, but didn't find it anywhere. I knew it exists only from your comment here.

**Comment by fbosnic** [comment]
Added to help. Would probably be nicer if it is a flag and not hard-coded but it is a bit complicated to change so I'll leave it like this for now

**Comment by fbosnic** [comment]
Rebased because of the conflicts with the other pull request

**Comment by eliobartos** [comment]
Ok it works. It is a bit weird why this option is not listed as option or something like that instead of a new command, but as you say it is complicated so... it works so ok.
Screenshot 2022-04-04 at 10 42 10

**Pull request merged**
